name: CI

on:
  push:
    branches: [ main, dev, jmcla012/testing/test-cases ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build tests
      run: |
        cmake .
        make

    - name: Run Board tests
      run: |
        ./tests/bin/runBoardTests

    - name: Run GameOver tests
      run: |
        ./tests/bin/runGameOverTests

    - name: Run GamePlayObject tests
      run: |
        ./tests/bin/runGameplayObjectTests

    - name: Run Game tests
      run: |
        ./tests/bin/runGameTests

    - name: Run Lane tests
      run: |
        ./tests/bin/runLaneTests

    - name: Run Leaderboard tests
      run: |
        ./tests/bin/runLeaderboardTests

    - name: Run Menu tests
      run: |
        ./tests/bin/runMenuTests

    - name: Run Pause Screen tests
      run: |
        ./tests/bin/runPauseScreenTests

    - name: Run Player tests
      run: |
        ./tests/bin/runPlayerTests

    - name: Run Screen tests
      run: |
        ./tests/bin/runScreenTests

    - name: Run Vehicle tests
      run: |      
        ./tests/bin/runVehicleTests



        
