name: CI

on:
  push:
    branches: [ main, dev, jmcla012/testing/test-cases ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build tests for the Leaderboard class
      run: |
        cmake .
        make

    - name: Run Leaderboard tests
      run: ./tests/bin/runLeaderboardTests

    - name: Run Lane tests
      run: | 
        ./tests/bin/runLaneTests

    - name: Run Menu tests
      run: | 
        ./tests/bin/runMenuTests

    - name: Run Board tests
      run: | 
        ./tests/bin/runBoardTests
        